import React from "react";
import type { Metadata } from "next";
import Head from 'next/head';
import GridOverlay from '../components/GridOverlay';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: "Blume",
  description: "Generated by create next app",
  // Open Graph
  openGraph: {
    title: "Blume - Home",
    description: "Generated by create next app",
    type: "website",
    locale: "fr_FR",
    url: "https://example.com",
    images: [
      {
        url: "https://example.com/og-image.jpg",
        width: 1200,
        height: 600,
        alt: "Image of the og:image",
      }
    ],
  },
  // Twitter
  twitter: {
    card: "summary_large_image",
    title: "Starter Next tailwind",
    description: "Generated by create next app",
    images: "https://example.com/og-image.jpg",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <Head>
        {/* Ajouter la balise link pour la police */}
        <link
          href="https://fonts.cdnfonts.com/css/helvetica-neue-55?styles=16015,16020,15990,15991,30124,30133"
          rel="stylesheet"
        />
      </Head>
      <body suppressHydrationWarning={true} className="min-h-screen bg-white">
        <GridOverlay />
        {/* Grille principale avec 4 colonnes sur mobile et 12 colonnes sur desktop */}
        <div className="grid grid-cols-4 md:grid-cols-12 gap-4 px-8 md:px-[80px] max-w-[1920px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
