import React from "react";
import type { Metadata } from "next";
import GridOverlay from '../components/GridOverlay';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: "Blume",
  description: "Generated by create next app",
  // Open Graph
  openGraph: {
    title: "Blume - Home",
    description: "Generated by create next app",
    type: "website",
    locale: "fr_FR",
    url: "https://example.com",
    images: [
      {
        url: "https://example.com/og-image.jpg",
        width: 1200,
        height: 600,
        alt: "Image of the og:image",
      }
    ],
  },
  // Twitter
  twitter: {
    card : "summary_large_image",
    title: "Starter Next tailwind",
    description: "Generated by create next app",
    images: "https://example.com/og-image.jpg",
  },
};

export default function RootLayout({children, padding = "px-8 lg:px-20"}: Readonly<{ children: React.ReactNode; padding?: string }>) {

  
  return (
    <html lang="fr">
      <body suppressHydrationWarning={true} className={padding}>
        <GridOverlay />
          {children}
      </body>
    </html>
  );
}
